gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken # This is the class name of the refresh token, you will need to adjust this to match the class your application will use
  ttl: 2592000
  ttl_update: true
  single_use: true
  cookie:
    enabled: true
    same_site: strict               # default value
    path: /                      # default value
    domain: localhost                # default value
    http_only: true              # default value
    secure: false                 # default value
    remove_token_from_body: true # default value
